Feat | Test signup and signin APIs
APIYOJENNIFER/post-it-backend pull request #14
Opened 2024-03-04 10:14 UTC by APIYOJENNIFER

Regarding issue #12, merging this will add tests for the API endpoints for signing up and signing in a user.

2024-03-04 13:10 UTC, ThatcherK requested changes

2024-03-04 13:10 UTC, ThatcherK commented on requirements.txt
> +pytest==8.0.2
Is there need to install pytest separately, when using pytest-django, it's alreasdy a dependency of pytest-django so it's installed by pytest-django

2024-03-04 13:10 UTC, ThatcherK commented on user/tests/test_users_api.py
> +def test_user_signup_api(client):
Please separate the signup test from signin. That helps narrow down troubleshooting, so that if a signin test fails, you know the problem is only with signin and vice verser

2024-03-04 21:00 UTC, APIYOJENNIFER commented on requirements.txt
> +pytest==8.0.2
An oversight on my end. I'll remove it

2024-03-05 06:13 UTC, ThatcherK approved these changes

2024-03-05 07:14 UTC, merged