Test groups API
APIYOJENNIFER/post-it-backend pull request #15
Opened 2024-03-05 20:00 UTC by APIYOJENNIFER

Merging this PR (issue #3) adds functionality for testing the group creation API

2024-03-06 10:57 UTC, ThatcherK requested changes

2024-03-06 10:57 UTC, ThatcherK commented on tests/test_groups_api.py
> +def test_get_groups_api(api_client, authenticate_user_with_token):
I would rather the name suggests the functionality being tested as opposed to saying 'api' or the http method used. for example test_group_list

2024-03-06 10:57 UTC, ThatcherK commented on tests/test_groups_api.py
> +    assert response.status_code == status.HTTP_200_OK
Also an another assertion of perhaps the length of the list returned.

2024-03-07 18:51 UTC, wakibi reviewed
Read about code coverage vs test coverage. Also, [this](https://django-testing-docs.readthedocs.io/en/latest/coverage.html) maybe a good place to start implementing; make sure the test coverage is about 70% or more

2024-03-12 15:42 UTC, wakibi reviewed
One more addition, add a CI pipeline (using github actions) to have these tests run on every code pushed.

2024-03-18 19:00 UTC, wakibi approved these changes

2024-03-19 08:22 UTC, APIYOJENNIFER commented
@ThatcherK please review the changes requested when you get time

2024-03-25 08:51 UTC, ThatcherK commented
@APIYOJENNIFER rebase

2024-03-25 12:27 UTC, APIYOJENNIFER commented
> @APIYOJENNIFER rebase

Done

2024-03-28 06:45 UTC, APIYOJENNIFER commented
@ThatcherK I'm done with rebasing

2024-03-28 07:59 UTC, ThatcherK approved these changes

2024-03-28 08:26 UTC, merged