Signup user API
APIYOJENNIFER/post-it-backend pull request #5
Opened 2023-10-24 08:38 UTC by APIYOJENNIFER

Add user model and create signup user API

2023-10-24 09:01 UTC, ThatcherK requested changes

2023-10-24 09:01 UTC, ThatcherK commented on post_it_backend/urls.py
> +    path('api/', include('user.urls')),
Here instead of having the route `api` point to the user app urls, create an api app, create a urls file inside that directory, and import all routes from the different directories. such that for any api route accessed is accessed through api for example `api/user/signup`, `api/message/` and so on.
So this particular line would change to `path('api/', include('api.urls'))`
 Then inside the api app in the urls file, the user routes can be added as `path('user/', include('user.urls'))`

2023-10-24 09:01 UTC, ThatcherK commented on user/migrations/0001_initial.py
> +                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
What's BigAutoField?

2023-10-24 09:01 UTC, ThatcherK commented on user/views.py
> +def create_user(request):
How are you handling password saving, I would expect the password to be encrypted, as it is not safe to store passwords as normal strings?

2023-10-24 09:08 UTC, ThatcherK commented
@APIYOJENNIFER  check this out about password encyption https://stackoverflow.com/questions/61546030/how-to-encrypt-password-before-saving-it-to-user-model-django

2023-10-24 09:11 UTC, APIYOJENNIFER commented on user/migrations/0001_initial.py
> +                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
I didn't explicitly include ID as a field in the User model. The BigAutoField field type was automatically added after running migrations which means that the field will hold 64-bit integers.

2023-10-25 10:03 UTC, ThatcherK approved these changes

2023-10-26 10:44 UTC, merged